### ISSUE TITLE
encoding

### ISSUE THREAD

**Issue by quantnlp** [LouYu2015/analysis_on_the_story_of_a_stone#1]
I tried to run the code on hlm.txt, but got an error when reading hlm.txt.
I use python 3.

If I change encoding to UTF-8 input_file = open(inFile, "r", encoding='utf8'), I can read the file.
However, the dict.csv file will be a mess.

Could you explain how you wrote to the hlm.txt file? Thanks!

**Comment by LouYu2015** [comment]
Please try preprocess_windows.py with hlm_ANSI.txt

**Comment by LouYu2015** [comment]
Closed for inactivity.
